[package]
name = "objekt"
version = "0.1.1" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Clone trait that is object-safe"
repository = "https://github.com/dtolnay/objekt"
documentation = "https://docs.rs/objekt"
